---
- name: Установка Zabbix Agent на группу серверов web
  hosts: web
  become: true
  vars:
    zabbix_server: 10.10.4.5
  tasks:
    - name: Загрузка Zabbix репозитория
      shell: wget https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb
      args:
        chdir: /tmp  

    - name: Установка Zabbix репозитория
      shell: dpkg -i zabbix-release_6.0-5+debian12_all.deb
      args:
        chdir: /tmp
        
    - name: Обновление пакетов
      apt:
        update_cache: yes
  
    - name: Установка необходимых пакетов
      apt:
        name: zabbix-agent
        state: present
                
    - name: Создание директории для логов Zabbix Agent
      command: mkdir -p /var/log/zabbix/
      become_user: root

    - name: Установка прав на директорию логов Zabbix Agent
      command: chown zabbix /var/log/zabbix/
      become_user: root

    - name: Копирование конфигурационного файла Zabbix Agent
      template:
        src: /home/user/ansible/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
